// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace labathome{
export enum FbConfiguration{
  NONE= 0,
  FbAnd2Configuration= 1,
  FbOr2Configuration= 2,
  FbAnd3Configuration= 3,
  FbNotConfiguration= 4,
  FbTonConfiguration= 5,
  FbRSConfiguration= 6
}};

/**
 * @constructor
 */
export namespace labathome{
export class FbExecutable {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbExecutable
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbExecutable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbExecutable= obj
 * @returns FbExecutable
 */
static getRootAsFbExecutable(bb:flatbuffers.ByteBuffer, obj?:FbExecutable):FbExecutable {
  return (obj || new FbExecutable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbExecutable= obj
 * @returns FbExecutable
 */
static getSizePrefixedRootAsFbExecutable(bb:flatbuffers.ByteBuffer, obj?:FbExecutable):FbExecutable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbExecutable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns flatbuffers.Long
 */
id():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
timestamp():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param number index
 * @returns labathome.FbConfiguration
 */
fbConfigType(index: number):labathome.FbConfiguration|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /**  */ (this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)) : /**  */ (0);
};

/**
 * @returns number
 */
fbConfigTypeLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
fbConfigTypeArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @param flatbuffers.Table= obj
 * @returns ?flatbuffers.Table
 */
fbConfig<T extends flatbuffers.Table>(index: number, obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
};

/**
 * @returns number
 */
fbConfigLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
maxBinaryIndex():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
maxIntegerIndex():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
maxDoubleIndex():number {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbExecutable(builder:flatbuffers.Builder) {
  builder.startObject(7);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long id
 */
static addId(builder:flatbuffers.Builder, id:flatbuffers.Long) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long timestamp
 */
static addTimestamp(builder:flatbuffers.Builder, timestamp:flatbuffers.Long) {
  builder.addFieldInt64(1, timestamp, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset fbConfigTypeOffset
 */
static addFbConfigType(builder:flatbuffers.Builder, fbConfigTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fbConfigTypeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<labathome.FbConfiguration> data
 * @returns flatbuffers.Offset
 */
static createFbConfigTypeVector(builder:flatbuffers.Builder, data:labathome.FbConfiguration[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startFbConfigTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset fbConfigOffset
 */
static addFbConfig(builder:flatbuffers.Builder, fbConfigOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, fbConfigOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createFbConfigVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startFbConfigVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number maxBinaryIndex
 */
static addMaxBinaryIndex(builder:flatbuffers.Builder, maxBinaryIndex:number) {
  builder.addFieldInt16(4, maxBinaryIndex, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number maxIntegerIndex
 */
static addMaxIntegerIndex(builder:flatbuffers.Builder, maxIntegerIndex:number) {
  builder.addFieldInt16(5, maxIntegerIndex, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number maxDoubleIndex
 */
static addMaxDoubleIndex(builder:flatbuffers.Builder, maxDoubleIndex:number) {
  builder.addFieldInt16(6, maxDoubleIndex, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbExecutable(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishFbExecutableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedFbExecutableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createFbExecutable(builder:flatbuffers.Builder, id:flatbuffers.Long, timestamp:flatbuffers.Long, fbConfigTypeOffset:flatbuffers.Offset, fbConfigOffset:flatbuffers.Offset, maxBinaryIndex:number, maxIntegerIndex:number, maxDoubleIndex:number):flatbuffers.Offset {
  FbExecutable.startFbExecutable(builder);
  FbExecutable.addId(builder, id);
  FbExecutable.addTimestamp(builder, timestamp);
  FbExecutable.addFbConfigType(builder, fbConfigTypeOffset);
  FbExecutable.addFbConfig(builder, fbConfigOffset);
  FbExecutable.addMaxBinaryIndex(builder, maxBinaryIndex);
  FbExecutable.addMaxIntegerIndex(builder, maxIntegerIndex);
  FbExecutable.addMaxDoubleIndex(builder, maxDoubleIndex);
  return FbExecutable.endFbExecutable(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbAnd2Configuration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbAnd2Configuration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbAnd2Configuration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbAnd2Configuration= obj
 * @returns FbAnd2Configuration
 */
static getRootAsFbAnd2Configuration(bb:flatbuffers.ByteBuffer, obj?:FbAnd2Configuration):FbAnd2Configuration {
  return (obj || new FbAnd2Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbAnd2Configuration= obj
 * @returns FbAnd2Configuration
 */
static getSizePrefixedRootAsFbAnd2Configuration(bb:flatbuffers.ByteBuffer, obj?:FbAnd2Configuration):FbAnd2Configuration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbAnd2Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
inputA():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
inputB():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbAnd2Configuration(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputA
 */
static addInputA(builder:flatbuffers.Builder, inputA:number) {
  builder.addFieldInt16(0, inputA, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputB
 */
static addInputB(builder:flatbuffers.Builder, inputB:number) {
  builder.addFieldInt16(1, inputB, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(2, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbAnd2Configuration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbAnd2Configuration(builder:flatbuffers.Builder, inputA:number, inputB:number, output:number):flatbuffers.Offset {
  FbAnd2Configuration.startFbAnd2Configuration(builder);
  FbAnd2Configuration.addInputA(builder, inputA);
  FbAnd2Configuration.addInputB(builder, inputB);
  FbAnd2Configuration.addOutput(builder, output);
  return FbAnd2Configuration.endFbAnd2Configuration(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbOr2Configuration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbOr2Configuration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbOr2Configuration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbOr2Configuration= obj
 * @returns FbOr2Configuration
 */
static getRootAsFbOr2Configuration(bb:flatbuffers.ByteBuffer, obj?:FbOr2Configuration):FbOr2Configuration {
  return (obj || new FbOr2Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbOr2Configuration= obj
 * @returns FbOr2Configuration
 */
static getSizePrefixedRootAsFbOr2Configuration(bb:flatbuffers.ByteBuffer, obj?:FbOr2Configuration):FbOr2Configuration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbOr2Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
inputA():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
inputB():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbOr2Configuration(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputA
 */
static addInputA(builder:flatbuffers.Builder, inputA:number) {
  builder.addFieldInt16(0, inputA, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputB
 */
static addInputB(builder:flatbuffers.Builder, inputB:number) {
  builder.addFieldInt16(1, inputB, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(2, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbOr2Configuration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbOr2Configuration(builder:flatbuffers.Builder, inputA:number, inputB:number, output:number):flatbuffers.Offset {
  FbOr2Configuration.startFbOr2Configuration(builder);
  FbOr2Configuration.addInputA(builder, inputA);
  FbOr2Configuration.addInputB(builder, inputB);
  FbOr2Configuration.addOutput(builder, output);
  return FbOr2Configuration.endFbOr2Configuration(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbAnd3Configuration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbAnd3Configuration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbAnd3Configuration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbAnd3Configuration= obj
 * @returns FbAnd3Configuration
 */
static getRootAsFbAnd3Configuration(bb:flatbuffers.ByteBuffer, obj?:FbAnd3Configuration):FbAnd3Configuration {
  return (obj || new FbAnd3Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbAnd3Configuration= obj
 * @returns FbAnd3Configuration
 */
static getSizePrefixedRootAsFbAnd3Configuration(bb:flatbuffers.ByteBuffer, obj?:FbAnd3Configuration):FbAnd3Configuration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbAnd3Configuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
inputA():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
inputB():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
inputC():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbAnd3Configuration(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputA
 */
static addInputA(builder:flatbuffers.Builder, inputA:number) {
  builder.addFieldInt16(0, inputA, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputB
 */
static addInputB(builder:flatbuffers.Builder, inputB:number) {
  builder.addFieldInt16(1, inputB, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputC
 */
static addInputC(builder:flatbuffers.Builder, inputC:number) {
  builder.addFieldInt16(2, inputC, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(3, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbAnd3Configuration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbAnd3Configuration(builder:flatbuffers.Builder, inputA:number, inputB:number, inputC:number, output:number):flatbuffers.Offset {
  FbAnd3Configuration.startFbAnd3Configuration(builder);
  FbAnd3Configuration.addInputA(builder, inputA);
  FbAnd3Configuration.addInputB(builder, inputB);
  FbAnd3Configuration.addInputC(builder, inputC);
  FbAnd3Configuration.addOutput(builder, output);
  return FbAnd3Configuration.endFbAnd3Configuration(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbNotConfiguration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbNotConfiguration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbNotConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbNotConfiguration= obj
 * @returns FbNotConfiguration
 */
static getRootAsFbNotConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbNotConfiguration):FbNotConfiguration {
  return (obj || new FbNotConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbNotConfiguration= obj
 * @returns FbNotConfiguration
 */
static getSizePrefixedRootAsFbNotConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbNotConfiguration):FbNotConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbNotConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
input():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbNotConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param number input
 */
static addInput(builder:flatbuffers.Builder, input:number) {
  builder.addFieldInt16(0, input, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(1, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbNotConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbNotConfiguration(builder:flatbuffers.Builder, input:number, output:number):flatbuffers.Offset {
  FbNotConfiguration.startFbNotConfiguration(builder);
  FbNotConfiguration.addInput(builder, input);
  FbNotConfiguration.addOutput(builder, output);
  return FbNotConfiguration.endFbNotConfiguration(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbTonConfiguration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbTonConfiguration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbTonConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbTonConfiguration= obj
 * @returns FbTonConfiguration
 */
static getRootAsFbTonConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbTonConfiguration):FbTonConfiguration {
  return (obj || new FbTonConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbTonConfiguration= obj
 * @returns FbTonConfiguration
 */
static getSizePrefixedRootAsFbTonConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbTonConfiguration):FbTonConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbTonConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
input():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
presetTimeSecs():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
elapsedTimeSecs():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbTonConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number input
 */
static addInput(builder:flatbuffers.Builder, input:number) {
  builder.addFieldInt16(0, input, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(1, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number presetTimeSecs
 */
static addPresetTimeSecs(builder:flatbuffers.Builder, presetTimeSecs:number) {
  builder.addFieldInt32(2, presetTimeSecs, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number elapsedTimeSecs
 */
static addElapsedTimeSecs(builder:flatbuffers.Builder, elapsedTimeSecs:number) {
  builder.addFieldInt32(3, elapsedTimeSecs, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbTonConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbTonConfiguration(builder:flatbuffers.Builder, input:number, output:number, presetTimeSecs:number, elapsedTimeSecs:number):flatbuffers.Offset {
  FbTonConfiguration.startFbTonConfiguration(builder);
  FbTonConfiguration.addInput(builder, input);
  FbTonConfiguration.addOutput(builder, output);
  FbTonConfiguration.addPresetTimeSecs(builder, presetTimeSecs);
  FbTonConfiguration.addElapsedTimeSecs(builder, elapsedTimeSecs);
  return FbTonConfiguration.endFbTonConfiguration(builder);
}
}
}
/**
 * @constructor
 */
export namespace labathome{
export class FbRSConfiguration {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FbRSConfiguration
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FbRSConfiguration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbRSConfiguration= obj
 * @returns FbRSConfiguration
 */
static getRootAsFbRSConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbRSConfiguration):FbRSConfiguration {
  return (obj || new FbRSConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FbRSConfiguration= obj
 * @returns FbRSConfiguration
 */
static getSizePrefixedRootAsFbRSConfiguration(bb:flatbuffers.ByteBuffer, obj?:FbRSConfiguration):FbRSConfiguration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FbRSConfiguration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
inputR():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
inputS():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
output():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFbRSConfiguration(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputR
 */
static addInputR(builder:flatbuffers.Builder, inputR:number) {
  builder.addFieldInt16(0, inputR, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number inputS
 */
static addInputS(builder:flatbuffers.Builder, inputS:number) {
  builder.addFieldInt16(1, inputS, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number output
 */
static addOutput(builder:flatbuffers.Builder, output:number) {
  builder.addFieldInt16(2, output, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFbRSConfiguration(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFbRSConfiguration(builder:flatbuffers.Builder, inputR:number, inputS:number, output:number):flatbuffers.Offset {
  FbRSConfiguration.startFbRSConfiguration(builder);
  FbRSConfiguration.addInputR(builder, inputR);
  FbRSConfiguration.addInputS(builder, inputS);
  FbRSConfiguration.addOutput(builder, output);
  return FbRSConfiguration.endFbRSConfiguration(builder);
}
}
}
